import {
    TeamWrapper,
    TeamTexts,
    TeamTextsTitle,
    TeamTextsText,
    TeamCardsWrapper,
    TeamCardWrapper,
    ProfilePictureWrapper,
    ProfileCircle,
    ProfileImage,
    TeamCardTextsNameWrapper,
    TeamCardTextsName,
    TeamCardTextsProffesion,
    TeamCardDescription,
    SocialMediaWrapper,
    Line,
    ContactInfoSocialMediaIconWrapper,
    ContactInfoSocialMediaIcon,

} from "./team.styles";

export {
    TeamWrapper,
    TeamTexts,
    TeamTextsTitle,
    TeamTextsText,
    TeamCardsWrapper,
    TeamCardWrapper,
    ProfilePictureWrapper,
    ProfileCircle,
    ProfileImage,
    TeamCardTextsNameWrapper,
    TeamCardTextsName,
    TeamCardTextsProffesion,
    TeamCardDescription,
    SocialMediaWrapper,
    Line,
    ContactInfoSocialMediaIconWrapper,
    ContactInfoSocialMediaIcon,
    
}
