import {
    FooterWrapper,
    BackgroundColor,
    FooterContainer,
    LogoNewsWrapper,
    LogoWrapper,
    LogoWrapperTexts,
    LogoWrapperTextsTitle,
    LogoWrapperTextsDescription,
    SocialMediaWrapper,
    Line,
    ContactInfoFacebookIconWrapper,
    ContactInfoFacebookIcon,
    LinksWrapper,
    LinksTitle,
    FooterMenuText,
    NewsWrapper,
    NewsWrapperTexts,
    NewsWrapperTitle,
    NewsWrapperText,
    FooterLine,
    FooterCopyrightTextWrapper,
    FooterCopyrightIcon,
    FooterCopyrightText,


} from "./footer.styles";


export {
    FooterWrapper,
    BackgroundColor,
    FooterContainer,
    LogoNewsWrapper,
    LogoWrapper,
    LogoWrapperTexts,
    LogoWrapperTextsTitle,
    LogoWrapperTextsDescription,
    SocialMediaWrapper,
    Line,
    ContactInfoFacebookIconWrapper,
    ContactInfoFacebookIcon,
    LinksWrapper,
    LinksTitle,
    FooterMenuText,
    NewsWrapper,
    NewsWrapperTexts,
    NewsWrapperTitle,
    NewsWrapperText,
    FooterLine,
    FooterCopyrightTextWrapper,
    FooterCopyrightIcon,
    FooterCopyrightText,

}
