import {
    HeaderWrapper,
    ContactsInfoWrapper,
    
    ContactsInfoWrapperLeft,
    ContactInfoMailWrapper,
    ContactInfoMailIconWrapper,
    ContactInfoMailIcon,
    ContactInfoMailText,
    ContactInfoPhoneWrapper,
    ContactInfoPhoneIconWrapper,
    ContactInfoPhoneIcon,
    ContactInfoPhoneText,

    ContactsInfoWrapperRight,
    ContactInfoFacebookIconWrapper,
    ContactInfoFacebookIcon,
    ContactInfoInstagramIconWrapper,
    ContactInfoInstagramIcon,
    ContactInfoTwitterIconWrapper,
    ContactInfoTwitterIcon,
    ContactInfoYoutubeIconWrapper,
    ContactInfoYoutubeIcon,

    HeaderInfo,
    HeaderInfoTextsWrapper,
    HeaderInfoTextsTitle,
    HeaderInfoTextsParagraph,
    HeaderInfoTextsDownload,
    HeaderInfoImgWrapper,
    HeaderInfoImg,
    OnlineStoresWrapper,
    GooglePlayWrapper,
    GooglePlayImg,
    AppStoreWrapper,
    AppStoreImg,

} from "../HeaderStyles/header.styles";

export {
    HeaderWrapper,
    ContactsInfoWrapper,

    ContactsInfoWrapperLeft,
    ContactInfoMailWrapper,
    ContactInfoMailIconWrapper,
    ContactInfoMailIcon,
    ContactInfoMailText,
    ContactInfoPhoneWrapper,
    ContactInfoPhoneIconWrapper,
    ContactInfoPhoneIcon,
    ContactInfoPhoneText,

    ContactsInfoWrapperRight,
    ContactInfoFacebookIconWrapper,
    ContactInfoFacebookIcon,    
    ContactInfoInstagramIconWrapper,
    ContactInfoInstagramIcon,
    ContactInfoTwitterIconWrapper,
    ContactInfoTwitterIcon,
    ContactInfoYoutubeIconWrapper,
    ContactInfoYoutubeIcon,

    HeaderInfo,
    HeaderInfoTextsWrapper,
    HeaderInfoTextsTitle,
    HeaderInfoTextsParagraph,
    HeaderInfoTextsDownload,
    HeaderInfoImgWrapper,
    HeaderInfoImg,
    OnlineStoresWrapper,
    GooglePlayWrapper,
    GooglePlayImg,
    AppStoreWrapper,
    AppStoreImg,

}